Repository sun-asterisk-research/table_reconstruction, pull requests merged in 2021-09, with the labels that each got.

#2 Initialize the module, add auxiliary files
  .gitignore
  .sun-ci.yml
  LICENSE
  MANIFEST.in
  pyproject.toml
  requirements.txt
  setup.cfg
  setup.py
  table_reconstruction/__init__.py
  tests/__init__.py
  tests/test_package.py
  tox.ini
Labels: feature, epic

#12 fix: missing submodule when installing manually, update config used by CI tools
  .flake8
  .sun-ci.yml
  pyproject.toml
  setup.py
  table_reconstruction/__init__.py
  tests/test_package.py
  tox.ini
Labels: bug

#13 feat: define package output
  requirements.txt
  setup.py
  table_reconstruction/__init__.py
  table_reconstruction/output/__init__.py
  table_reconstruction/output/cell.py
  table_reconstruction/output/element.py
  table_reconstruction/output/table.py
Labels: feature

#16 chore: add auto-version and auto-generate document
  .gitignore
  .sun-ci.yml
  docs/source/Makefile
  docs/source/_static/.gitkeep
  docs/source/_templates/.gitkeep
  docs/source/conf.py
  docs/source/index.rst
  setup.cfg
  setup.py
  table_reconstruction/__init__.py
  table_reconstruction/output/cell.py
  table_reconstruction/output/element.py
  table_reconstruction/output/table.py
  tox.ini
Labels: documentation

#21 chore: downgrade Tox and state the exact versions of the libraries used in the CI process
  .sun-ci.yml
  tox.ini
Labels: bug

#10 feat: add a module for detecting table region
  .sun-ci.yml
  table_reconstruction/table_detection/__init__.py
  table_reconstruction/table_detection/detector.py
  table_reconstruction/table_detection/postprocess.py
  table_reconstruction/table_detection/preprocess.py
  table_reconstruction/table_detection/utils.py
  table_reconstruction/table_detection/yolov5/__init__.py
  table_reconstruction/table_detection/yolov5/hubconf.py
  table_reconstruction/table_detection/yolov5/models/__init__.py
  table_reconstruction/table_detection/yolov5/models/common.py
  table_reconstruction/table_detection/yolov5/models/experimental.py
  table_reconstruction/table_detection/yolov5/models/utils.py
  table_reconstruction/table_detection/yolov5/models/yolo.py
  tox.ini
Labels: feature

#27 Release version 0.0.1
  .flake8
  .gitignore
  .sun-ci.yml
  LICENSE
  MANIFEST.in
  docs/source/Makefile
  docs/source/_static/.gitkeep
  docs/source/_templates/.gitkeep
  docs/source/conf.py
  docs/source/index.rst
  example/.gitkeep
  example/example.ipynb
  example/table.png
  pyproject.toml
  requirements.txt
  setup.cfg
  setup.py
  table_reconstruction/__init__.py
  table_reconstruction/line_segmentation/__init__.py
  table_reconstruction/line_segmentation/line_segment.py
  table_reconstruction/line_segmentation/unet/__init__.py
  table_reconstruction/line_segmentation/unet/resunet.py
  table_reconstruction/line_segmentation/unet/unet_parts.py
  table_reconstruction/line_segmentation/utils.py
  table_reconstruction/output/__init__.py
  table_reconstruction/output/cell.py
  table_reconstruction/output/element.py
  table_reconstruction/output/table.py
  table_reconstruction/table_detection/__init__.py
  table_reconstruction/table_detection/detector.py
  table_reconstruction/table_detection/preprocess.py
  table_reconstruction/table_detection/utils.py
  table_reconstruction/table_detection/yolov5/__init__.py
  table_reconstruction/table_detection/yolov5/hubconf.py
  table_reconstruction/table_detection/yolov5/models/__init__.py
  table_reconstruction/table_detection/yolov5/models/common.py
  table_reconstruction/table_detection/yolov5/models/experimental.py
  table_reconstruction/table_detection/yolov5/models/utils.py
  table_reconstruction/table_detection/yolov5/models/yolo.py
  table_reconstruction/utils/__init__.py
  table_reconstruction/utils/cell_utils.py
  table_reconstruction/utils/lines_utils.py
  table_reconstruction/utils/mask_utils.py
  table_reconstruction/utils/table_utils.py
  tests/__init__.py
  tests/tableImg.jpg
  tests/test_line_segment.py
  tests/test_package.py
  tests/test_table_detection.py
  tox.ini
Labels: epic
